// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for OrderStatus.
const (
	ACTIVE        OrderStatus = "ACTIVE"
	CANCELLED     OrderStatus = "CANCELLED"
	FINISHED      OrderStatus = "FINISHED"
	PAYMENTFAILED OrderStatus = "PAYMENT_FAILED"
)

// Offer defines model for Offer.
type Offer struct {
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	Deposit        int        `json:"deposit"`
	ExpiresAt      time.Time  `json:"expires_at"`
	Id             string     `json:"id"`
	PricePerMinute int        `json:"price_per_minute"`
	PriceUnlock    int        `json:"price_unlock"`
	ScooterId      string     `json:"scooter_id"`
	UserId         string     `json:"user_id"`
	ZoneId         string     `json:"zone_id"`
}

// Order defines model for Order.
type Order struct {
	CurrentAmount   *int        `json:"current_amount"`
	Deposit         *int        `json:"deposit,omitempty"`
	DurationSeconds *int        `json:"duration_seconds"`
	FinishTime      *time.Time  `json:"finish_time"`
	Id              string      `json:"id"`
	OfferId         string      `json:"offer_id"`
	PricePerMinute  *int        `json:"price_per_minute,omitempty"`
	PriceUnlock     *int        `json:"price_unlock,omitempty"`
	ScooterId       string      `json:"scooter_id"`
	StartTime       time.Time   `json:"start_time"`
	Status          OrderStatus `json:"status"`
	UserId          string      `json:"user_id"`
}

// OrderStatus defines model for Order.Status.
type OrderStatus string

// PostOffersJSONBody defines parameters for PostOffers.
type PostOffersJSONBody struct {
	ScooterId string `json:"scooter_id"`
	UserId    string `json:"user_id"`
}

// PostOrdersJSONBody defines parameters for PostOrders.
type PostOrdersJSONBody struct {
	OfferId string `json:"offer_id"`
	UserId  string `json:"user_id"`
}

// PostOffersJSONRequestBody defines body for PostOffers for application/json ContentType.
type PostOffersJSONRequestBody PostOffersJSONBody

// PostOrdersJSONRequestBody defines body for PostOrders for application/json ContentType.
type PostOrdersJSONRequestBody PostOrdersJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создать оффер на самокат для пользователя
	// (POST /offers)
	PostOffers(w http.ResponseWriter, r *http.Request)
	// Создать заказ на основе оффера
	// (POST /orders)
	PostOrders(w http.ResponseWriter, r *http.Request)
	// Получить информацию о заказе
	// (GET /orders/{order_id})
	GetOrdersOrderId(w http.ResponseWriter, r *http.Request, orderId string)
	// Завершить заказ
	// (POST /orders/{order_id}/finish)
	PostOrdersOrderIdFinish(w http.ResponseWriter, r *http.Request, orderId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Создать оффер на самокат для пользователя
// (POST /offers)
func (_ Unimplemented) PostOffers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать заказ на основе оффера
// (POST /orders)
func (_ Unimplemented) PostOrders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить информацию о заказе
// (GET /orders/{order_id})
func (_ Unimplemented) GetOrdersOrderId(w http.ResponseWriter, r *http.Request, orderId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Завершить заказ
// (POST /orders/{order_id}/finish)
func (_ Unimplemented) PostOrdersOrderIdFinish(w http.ResponseWriter, r *http.Request, orderId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostOffers operation middleware
func (siw *ServerInterfaceWrapper) PostOffers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOffers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOrders operation middleware
func (siw *ServerInterfaceWrapper) PostOrders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrdersOrderId operation middleware
func (siw *ServerInterfaceWrapper) GetOrdersOrderId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order_id" -------------
	var orderId string

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", chi.URLParam(r, "order_id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrdersOrderId(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOrdersOrderIdFinish operation middleware
func (siw *ServerInterfaceWrapper) PostOrdersOrderIdFinish(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order_id" -------------
	var orderId string

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", chi.URLParam(r, "order_id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOrdersOrderIdFinish(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/offers", wrapper.PostOffers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orders", wrapper.PostOrders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders/{order_id}", wrapper.GetOrdersOrderId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orders/{order_id}/finish", wrapper.PostOrdersOrderIdFinish)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9yW204jRxPHX8Xq77u08djYJOs7QiCxtAGkRZGSFbKGmTb0xnNId0+0BFnipASJVVBy",
	"QxQpG+0bOAQvs4C9r1D9RlF1G9szHg7ORhtpb2DcU9VVXf9f1fQOcQIvDHzqS0FqO0Q4W9Sz9eNKs0k5",
	"PoQ8CCmXjOplh1NbUrdhS/xFn9te2KKkRspWuVKw5gqlylqpXJu1apb1NcmTZsA9NCWuLWlBMo+SPJHb",
	"IboIyZm/Sdp54tIwECy5Y8myhpbMl3STcjSlz0PGqbgvfqVWnXt4fOYmNwvw7IWPPn6UZRxy5tBGSHnD",
	"Y34kaSrrrKSNS+S3AuebhHk501w4QSApb6TTGqwXKtW5rMQikeGDi4VSeTbL4fvApxMOuFgoTZq384TT",
	"byPGqUtqT7Fko4iJlEf7JtTKKFyqMCMO1ofRg41n1JGY7Ap3M3mMOKe+bNheEPkyVVwrT/yo1bI38Kfk",
	"Ec2q9hTwuRG3JQv8hqBO4Lsi6fPAeE3mM7HV0CzegXC1elcL3RLmDqSxfAV7w8kCQfPe+DC6QEiby3ur",
	"O1udakAJacvIyO1HHvI/v7BW/3KR5MlSfbn+5PPFT0meLMwvLyw+fqyfV+e/+mJxea2xNF/HhfX8WCpD",
	"33dt4Sl6cijx8DCJUk12HG7O/GaAubhUOJyFiD6mv1rPwSVcQQxd6Kl9tQeX0Ie/oJ9Te9BVu3AGsdqD",
	"DibMpD7DE5NLbn61TvLkO8qF2as0Y81YGsGQ+nbISI3MzlgzeNbQllu65EWdu34MA6EbFSeA7sS6S2pk",
	"NRByxdiYglAhPwncbT0fAl9SMxjsMGwxR7sVnwkMf/PBmxwr72cEp/TLlC5bmZEb9r9eEGHgC5N92SpN",
	"dfb/c9okNfK/4ug2UBxcBYrmHqCDJjGAl+pQHaLeKHsfLuAcOtDDMlQsaxIb+B26CIraVbv4pPahp46h",
	"m4O30FG70IFr6Kp9tauOcxAjXjnoQRfO9N7X0IfX0DOMDYKpffUiB/2bNDBy1ZrNiPwLbqSOoAcxvElA",
	"akKcQ1/tqX11AG8RaS2MiDzP5tvo/uqWgOjcwe06Or1LNMjBOVypEzxUH67UC7iAPpzhG+jiC4TA3hQo",
	"t9NiqM46Rivq+Xwf48bm32L8H0z9d+N7bAbdbPSf061vFVl0n0IHFYWLB9L9cpwKpLajJ+Q5ApXguaPR",
	"j+HMoIbMWtnMqgNsBzSDnjpBqPrqCGL4ExO7B9KLYfoaUgQcuwejjhFsZvTtPBZ39P8Gc9uY4ibNIPMz",
	"OgBT/627enRz26NSA/10hzA8EI5zvLjY3vA6YlBIip0fEy5N0/oECNZ7AOFX6KlDHFtwDR31A8SD7h6r",
	"sTowXFQydDwdF6Kr1YA3Bou0hH/okXGgfoTYiBhPhP4plwgM3QfrVzT3zodMmIGQS8bhA5NzTA8s4xm2",
	"gTpSP9/d28O2S3jp1ozVifF8dKf66gBeo/4ZQbM/Wq+m/EqdjuUVp4ZAJiXt4eJE7N9Gt7vUnS6nv9V4",
	"7nN1nPr24XgZMTEI1F5v/x0AAP//1x18UmYQAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
