// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for OrderStatus.
const (
	ACTIVE        OrderStatus = "ACTIVE"
	CANCELLED     OrderStatus = "CANCELLED"
	FINISHED      OrderStatus = "FINISHED"
	PAYMENTFAILED OrderStatus = "PAYMENT_FAILED"
)

// Offer defines model for Offer.
type Offer struct {
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	Deposit        int        `json:"deposit"`
	ExpiresAt      time.Time  `json:"expires_at"`
	Id             string     `json:"id"`
	PricePerMinute int        `json:"price_per_minute"`
	PriceUnlock    int        `json:"price_unlock"`
	ScooterId      string     `json:"scooter_id"`
	UserId         string     `json:"user_id"`
	ZoneId         string     `json:"zone_id"`
}

// Order defines model for Order.
type Order struct {
	CurrentAmount   *int        `json:"current_amount"`
	Deposit         *int        `json:"deposit,omitempty"`
	DurationSeconds *int        `json:"duration_seconds"`
	FinishTime      *time.Time  `json:"finish_time"`
	Id              string      `json:"id"`
	OfferId         string      `json:"offer_id"`
	PricePerMinute  *int        `json:"price_per_minute,omitempty"`
	PriceUnlock     *int        `json:"price_unlock,omitempty"`
	ScooterId       string      `json:"scooter_id"`
	StartTime       time.Time   `json:"start_time"`
	Status          OrderStatus `json:"status"`
	UserId          string      `json:"user_id"`
}

// OrderStatus defines model for Order.Status.
type OrderStatus string

// PostOffersJSONBody defines parameters for PostOffers.
type PostOffersJSONBody struct {
	ScooterId string `json:"scooter_id"`
	UserId    string `json:"user_id"`
}

// PostOrdersJSONBody defines parameters for PostOrders.
type PostOrdersJSONBody struct {
	OfferId string `json:"offer_id"`
	OrderId string `json:"order_id"`
	UserId  string `json:"user_id"`
}

// PostOffersJSONRequestBody defines body for PostOffers for application/json ContentType.
type PostOffersJSONRequestBody PostOffersJSONBody

// PostOrdersJSONRequestBody defines body for PostOrders for application/json ContentType.
type PostOrdersJSONRequestBody PostOrdersJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Создать оффер на самокат для пользователя
	// (POST /offers)
	PostOffers(w http.ResponseWriter, r *http.Request)
	// Создать заказ на основе оффера
	// (POST /orders)
	PostOrders(w http.ResponseWriter, r *http.Request)
	// Получить информацию о заказе
	// (GET /orders/{order_id})
	GetOrdersOrderId(w http.ResponseWriter, r *http.Request, orderId string)
	// Завершить заказ
	// (POST /orders/{order_id}/finish)
	PostOrdersOrderIdFinish(w http.ResponseWriter, r *http.Request, orderId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Создать оффер на самокат для пользователя
// (POST /offers)
func (_ Unimplemented) PostOffers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать заказ на основе оффера
// (POST /orders)
func (_ Unimplemented) PostOrders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить информацию о заказе
// (GET /orders/{order_id})
func (_ Unimplemented) GetOrdersOrderId(w http.ResponseWriter, r *http.Request, orderId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Завершить заказ
// (POST /orders/{order_id}/finish)
func (_ Unimplemented) PostOrdersOrderIdFinish(w http.ResponseWriter, r *http.Request, orderId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostOffers operation middleware
func (siw *ServerInterfaceWrapper) PostOffers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOffers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOrders operation middleware
func (siw *ServerInterfaceWrapper) PostOrders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrdersOrderId operation middleware
func (siw *ServerInterfaceWrapper) GetOrdersOrderId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order_id" -------------
	var orderId string

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", chi.URLParam(r, "order_id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrdersOrderId(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOrdersOrderIdFinish operation middleware
func (siw *ServerInterfaceWrapper) PostOrdersOrderIdFinish(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "order_id" -------------
	var orderId string

	err = runtime.BindStyledParameterWithOptions("simple", "order_id", chi.URLParam(r, "order_id"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOrdersOrderIdFinish(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/offers", wrapper.PostOffers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orders", wrapper.PostOrders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders/{order_id}", wrapper.GetOrdersOrderId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orders/{order_id}/finish", wrapper.PostOrdersOrderIdFinish)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9yW204jRxPHX8Xq77u08djYJOs7QiCxtAGkRZGSFbKGmTbMxnNId0+0BFnipASJVVBy",
	"QxQpG+0bOAQvs4C9r1D9RlF1G9szbg7ORhtpb9DQruqqrv+vqnuHOKEfhQENBCe1HcKdLerb6nOl2aQM",
	"PyIWRpQJj6plh1FbULdhC/yPPrf9qEVJjZStcqVgzRVKlbVSuTZr1Szra5InzZD5aEpcW9CC8HxK8kRs",
	"R+jCBfOCTdLOE5dGIffSO5Ysa2jpBYJuUoam9HnkMcrvi1+pVeceHt9z05uFePbCRx8/MhlHzHNoI6Ks",
	"4XtBLGgma1PS2iUOWqHzTcq8bDTnThgKyhrZtAbrhUp1zpRYzA0+uFgolWdNDt+HAZ1wwMVCadK8nSeM",
	"fht7jLqk9hRLNoqYSnm0b0otQ+EyhRlxsD6MHm48o47AZFeYa+QxZowGomH7YRyITHGtPAniVsvewH8F",
	"i6mp2lPA58bMFl4YNDh1wsDlaZ8Hxmt6gce3GorFOxCuVu9qoVvC3IE0lq9gbzgmEBTvjQ+jC7iwmbi3",
	"urPVqQYUF7aItdxB7CP/8wtr9S8XSZ4s1ZfrTz5f/JTkycL88sLi48fqe3X+qy8Wl9caS/N1XFjPj6Uy",
	"9H3XFp6iJ4cSDw+TKtVkx+HmXtAMMReXcod5EaKP6a/Wc3AJV5BAF3pyX+7BJfThL+jn5B505S6cQSL3",
	"oIMJe0Kd4YnOJTe/Wid58h1lXO9VmrFmLIVgRAM78kiNzM5YM3jWyBZbquRFlbv6jEKuGhUngOrEuktq",
	"ZDXkYkXb6IJQLj4J3W01H8JAUD0Y7ChqeY5yKz7jGP7mwpscK+9nBGf0M0pnVmbkhv2vFngUBlxnX7ZK",
	"U539/4w2SY38rzh6DRQHT4GifgeooGkM4KU8lIeoN8rehws4hw70sAwVy5rEBn6HLoIid+Uufsl96Mlj",
	"6ObgLXTkLnTgGrpyX+7K4xwkiFcOetCFM7X3NfThNfQ0Y4Ngcl++yEH/Jg2MXLVmDZF/wY3kEfQggTcp",
	"SHWIc+jLPbkvD+AtIq2E4bHv22wb3V/dEhCdO7hdR6V3iQY5OIcreYKH6sOVfAEX0Icz/AW6+ANCYG9y",
	"lNtpeajOOkYrqvl8H+Pa5t9i/B9MfZVlY6q75d1aYhgwNcFu9vzPe0O9SUy9cQod5AEuHtgbL8eZQuY7",
	"ar6eI46pbuioxkngTIOKxFtm4uUBNhOaQU+eIJJ9eQQJ/ImJ3YP4xTB9hTi2B/YeRh3jX0/422ku7tzI",
	"18YUN6mB68/oAGv1t+6qwc9snwrVDk93iIcHwssAnz22PwROo5AWOz8mXBas9QkQrPcAwq/Qk4c49OAa",
	"OvIHSAazYazG8kBzUTHoeDouRFepAW80FlkJ/1AD50D+CIkWMZkI/VMuFRi6D9avqF+tD5lPAyGXtMMH",
	"JueYHljGM2wDeSR/vru3h22X8lKtmcgT7fnoTvXlAbxG/Q1BzVfeqynvuNOxvJLMEDBS0h4uTsT+bfQ2",
	"zLwIc+qmx3Ofy+PMzYnjZcTEIFB7vf13AAAA//8qn7jdpBAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
